import Head from 'next/head'
import Image from 'next/image'
import { Red_Hat_Display } from '@next/font/google'


import LineNumber from '../components/linenumber/line_number.jsx';
import UserImage from '../components/userimage/user_image.jsx';

export const redhat = Red_Hat_Display({ subsets: ['latin'], variable: '--red-hat-font'});

import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Meet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>
      <main className={`${redhat.variable} ${styles.main}`}>
        <header>
          <img src="/assets/logo.svg" alt="logo" />
          <section className={styles.hero}>
            <div className={styles.imgContainer}>
              <img src="/assets/desktop/image-hero-left.png" alt="hero" />
              <img src="/assets/desktop/image-hero-right.png" alt="hero" />
            </div>
            <img className={styles.desktopImage} src="/assets/desktop/image-hero-left.png" alt="hero" />
            <div className={styles.heroContent}>
              <h1 className={styles.title}>Group Chat for Everyone</h1>
              <p>Meet makes it easy to connect with others face-to-face virtually and collaborate across any device.</p>
              <div className={styles.ctaContainer}>
                <button className={`${styles.button} ${styles.buttonA}`}>Download <span>v1.3</span></button>
                <button className={`${styles.button} ${styles.buttonB}`}>What is it?</button>
              </div>
            </div>
            <img className={styles.desktopImage} src="/assets/desktop/image-hero-right.png" alt="hero" />
            
          </section>
        </header>

        <LineNumber>01</LineNumber>
        <UserImage></UserImage>

        <section className={styles.moreText}>
          <div>BUILT FOR MODERN USE</div>
          <h2>Smarter meetings, all in one place</h2>
          <p>Send messages, share files, show your screen, and record your meetings — all in one workspace. Control who can join with invite-only team access, data encryption, and data export.</p>
        </section>

        <LineNumber>02</LineNumber>

        <section className={styles.footer}>
          <div></div>
          <h3>Experience more together</h3>
          <p>Stay connected with reliable HD meetings and unlimited one-on-one and group video sessions.</p>
          <button className={`${styles.button} ${styles.buttonB}`}>Download <span>v1.3</span></button>
        </section>

      </main>
    </>
  )
}
